---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name termix-secret
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # cnpg
        DATABASE_DIALECT: postgres
        DATABASE_URL: "postgres://{{ .TERMIX_POSTGRES_USER }}:{{ .TERMIX_POSTGRES_PASS }}@postgres-18-rw.database.svc.cluster.local:5432/termix"
        DATABASE_POOL_MAX: "10"

        # postgres-init
        INIT_POSTGRES_DBNAME: &dbName termix
        INIT_POSTGRES_HOST: &dbHost postgres-18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser "{{ .TERMIX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .TERMIX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: termix
    - extract:
        key: cloudnativepg