---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-18

spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: local-path
  
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true

  postgresql:
    extensions:
      - name: timescaledb
        image:
          reference: ghcr.io/vember31/timescaledb:2.25.2
      - name: timescaledb-toolkit
        image:
          reference: ghcr.io/vember31/timescaledb-toolkit:1.22.0
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
      max_locks_per_transaction: '128'
      timescaledb.max_background_workers: '32'
      timescaledb.max_tuples_decompressed_per_dml_transaction: '0'
      timescaledb.telemetry_level: 'off'
    shared_preload_libraries:
      - timescaledb
 
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  
  monitoring:
    enablePodMonitor: true
  
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-18-backup

  # # The below is intended for upgrades. Read the readme for documentation about how to perform this upgrade going forward
  # bootstrap:
  #   initdb:
  #     import:
  #       type: monolith
  #       databases: ["*"]
  #       roles: ["*"]
  #       source:
  #         externalCluster: &previousCluster postgres17 #this might not matter. using servername.
  # externalClusters:
  #   - name: *previousCluster
  #     connectionParameters:
  #       host: postgres-18-rw.database.svc.cluster.local #service of the previous cluster
  #       user: postgres
  #       dbname: postgres
  #     password:
  #       name: cloudnative-pg-secret
  #       key: password