---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.0/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: donetick
  namespace: home
spec:
  name: Donetick
  description: Task and chore management
  launchUrl: https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}
  callbackUrls:
    - https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}/auth/oauth2
    - donetick://auth/oauth2
  allowedUserGroups:
    - name: donetick-users
      namespace: security
  secret:
    name: donetick-oidc-credentials
    additionalLabels:
      app.kubernetes.io/name: donetick
