---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.10.1/dist/schemas/helmrelease_v2_pocket-id-operator.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
  namespace: security
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
    namespace: flux-system

  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace

  rollback:
    recreate: true
    cleanupOnFail: true

  uninstall:
    keepHistory: false

  maxHistory: 1

  values:
    operator:
      timezone: ${TIMEZONE}
      autoGenerateLogos: true
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi

    metrics:
      enabled: false

    instance:
      enabled: false
