---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-keys
  namespace: security

spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore

  refreshInterval: "1h"
  target:
    name: crowdsec-keys
    creationPolicy: 'Owner'
    template:
      data:
        ENROLL_KEY: "{{ .CROWDSEC_ENROLLMENT_KEY }}"
        BOUNCER_KEY_traefik: "{{ .CROWDSEC_BOUNCER_KEY_TRAEFIK }}"
        CROWDSEC_WEBUI_LAPI_PASSWORD: "{{ .CROWDSEC_WEBUI_LAPI_PASSWORD }}"

  dataFrom:
    - extract:
        key: crowdsec