---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name autobrr-secret
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # cnpg
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: &dbName autobrr
        AUTOBRR__POSTGRES_HOST: &dbHost postgres-18-rw.database.svc.cluster.local
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__POSTGRES_USER: &dbUser "{{ .AUTOBRR_POSTGRES_USER }}"
        AUTOBRR__POSTGRES_PASS: &dbPass "{{ .AUTOBRR_POSTGRES_PASS }}"
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"

        # postgres-init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # OIDC
        AUTOBRR__OIDC_ENABLED: "false"
        AUTOBRR__OIDC_ISSUER: ""
        AUTOBRR__OIDC_CLIENT_ID: "{{ .AUTOBRR__OIDC_CLIENT_ID }}"
        AUTOBRR__OIDC_CLIENT_SECRET: "{{ .AUTOBRR__OIDC_CLIENT_SECRET }}"
        AUTOBRR__OIDC_REDIRECT_URL: "https://autobrr.local.${SECRET_DOMAIN}/api/auth/oidc/callback"
        AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: "false"
        
  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: cloudnativepg