---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup
  namespace: storage
spec:
  cron: "10 7 * * *" #UTC
  task: "backup"
  groups:
  - default
  retain: 1
  concurrency: 2