# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: grafana-admin-credentials
    creationPolicy: Merge
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: grafana
        property: GF_SECURITY_ADMIN_USER
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: grafana
        property: GF_SECURITY_ADMIN_PASSWORD
