---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
    folders: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    log:
      mode: console
    server:
      root_url: https://grafana.local.${SECRET_DOMAIN}
    auth.anonymous:
      enabled: "true"
      org_name: Main Org.
      org_role: Viewer
      hide_version: "false"
    security:
      cookie_secure: "true"
      cookie_samesite: grafana
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      reporting_enabled: "false"
    explore:
      enabled: "true"
    feature_toggles:
      enable: publicDashboards
    news:
      news_feed_enabled: "false"
    panels:
      disable_sanitize_html: "true"
    plugins:
      allow_loading_unsigned_plugins: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel
    date_formats:
      use_browser_locale: "true"
      default_timezone: ${TIMEZONE}
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_INSTALL_PLUGINS
                  value: grafana-clock-panel,grafana-piechart-panel,grafana-worldmap-panel,natel-discrete-panel,pr0ps-trackmap-panel,vonage-status-panel,victoriametrics-logs-datasource
              envFrom:
                - secretRef:
                    name: grafana-secret
              resources:
                requests:
                  cpu: 100m
                limits:
                  memory: 256Mi
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: grafana
