---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  secretStoreRef:
      name: gitlab-secret-store
      kind: ClusterSecretStore
  target:
    name: bookboss-secret
    template:
      engineVersion: v2
      data:
        #bookboss
        BOOKBOSS__DATABASE__DATABASE_URL: postgres://{{ .BOOKBOSS_POSTGRES_USER }}:{{ .BOOKBOSS_POSTGRES_PASS }}@postgres-18-rw.database.svc.cluster.local:5432/${APP}?sslmode=disable
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: "{{ .BOOKBOSS_METADATA_HARDCOVER_API_TOKEN }}"

        #init-postgres
        INIT_POSTGRES_DBNAME: bookboss
        INIT_POSTGRES_HOST: postgres-18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .BOOKBOSS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .BOOKBOSS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        
  dataFrom:
    - extract:
        key: cloudnativepg
    - extract:
        key: bookboss