---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.0/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: donetick-users
  namespace: security
spec:
  friendlyName: Donetick Users
  customClaims:
    - key: app
      value: donetick
  users:
    userRefs:
      - name: dm
      - name: emm
