---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name autopulse
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace

  test:
    enable: true

  rollback:
    recreate: true
    cleanupOnFail: true

  uninstall:
    keepHistory: false

  maxHistory: 1

  values:

    controllers:
      ${APP}:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom:
              - secretRef:
                  name: autopulse-secret

        containers:
          app:
            image:
              repository: docker.io/danonline/autopulse
              tag: latest-postgres@sha256:98683d6925b7cb76753016ce5ab9e2021f19e2caa9771b6bc49d891a3c07078f
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      app:
        controller: *name
        forceRename: ${APP}-app
        ports:
          http:
            port: 2875

    ingress:
      app:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: traefik.local.${SECRET_DOMAIN}
          traefik.ingress.kubernetes.io/router.middlewares: networking-internal-with-errors@kubernetescrd,media-autopulse-redirect@kubernetescrd
          gethomepage.dev/enabled: "false"
          gethomepage.dev/description: "*Arr / Plex Bridge"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: https://github.com/dan-online/autopulse/raw/main/assets/logo.webp
          gethomepage.dev/name: Autopulse
          gethomepage.dev/siteMonitor: http://${APP}-app.media.svc.cluster.local:2875/ui/events

        hosts:
          - host: &host ${GATUS_SUBDOMAIN:-${APP}}.local.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Exact
                service:
                  identifier: app
                  port: http
              - path: /ui
                pathType: Prefix
                service:
                  identifier: app
                  port: http

        tls:
          - secretName: ${APP}-tls-production
            hosts:
              - *host

    persistence:
      config:
        type: secret
        name: autopulse-secret
        advancedMounts:
          ${APP}:
            app:
              - path: /app/config.yaml
                readOnly: true
                subPath: config.yaml
