---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name wizarr-secret
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIZARR_API_KEY: "{{ .WIZARR_API_KEY }}"
  dataFrom:
    - extract:
        key: wizarr
