---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bookboss-opds-auth
  namespace: networking
spec:
  headers:
    customResponseHeaders:
      WWW-Authenticate: 'Basic realm="BookBoss"'
