---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gatus-headers
  namespace: networking
spec:
  headers:
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: strict-origin-when-cross-origin
    permissionsPolicy: "camera=(), geolocation=(), microphone=(), payment=(), usb=()"
    contentSecurityPolicy: >-
      default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self';
      script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self';
      media-src 'self' blob:; frame-src 'self'; worker-src 'self' blob:; manifest-src 'self';
      upgrade-insecure-requests
    customResponseHeaders:
      Cross-Origin-Opener-Policy: same-origin
      Cross-Origin-Resource-Policy: same-origin
      X-Powered-By: ""
