---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: networking

spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore

  refreshInterval: "1h"
  target:
    name: crowdsec-bouncer-key
    creationPolicy: 'Owner'
    template:
      data:
        crowdsec-bouncer-key: "{{ .CROWDSEC_BOUNCER_KEY_TRAEFIK }}"

  dataFrom:
    - extract:
        key: crowdsec