---
- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
              service_group: Downloads # group name where widget exists
              service_name: Sonarr # service name for that widget
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
              service_group: Downloads # group name where widget exists
              service_name: Radarr # service name for that widget

- Home:
    - HomeAssistant:
        href: http://homeassistant.local:8123
        icon: home-assistant
        description: Home Assistant
        widget:
            type: homeassistant
            url: http://192.168.2.7:8123
            key: {{HOMEPAGE_VAR_HASS_TOKEN}}

- Infrastructure:
    - PVE1:
        href: https://${PVE_1}:8006
        icon: proxmox
        description: 'Proxmox: Node 1'
        widget:
          type: proxmox
          url: https://${PVE_1}:8006
          username: {{HOMEPAGE_VAR_PVE_TOKEN_ID}}
          password: {{HOMEPAGE_VAR_PVE_1_SECRET}}
          node: pve
    - PVE2:
        href: https://${PVE_1}:8006
        icon: proxmox
        description: 'Proxmox: Node 2'
        widget:
          type: proxmox
          url: https://${PVE_1}:8006
          username: {{HOMEPAGE_VAR_PVE_TOKEN_ID}}
          password: {{HOMEPAGE_VAR_PVE_1_SECRET}}
          node: pve2
    - PVE3:
        href: https://${PVE_1}:8006
        icon: proxmox
        description: 'Proxmox: Node 3'
        widget:
          type: proxmox
          url: https://${PVE_1}:8006
          username: {{HOMEPAGE_VAR_PVE_TOKEN_ID}}
          password: {{HOMEPAGE_VAR_PVE_1_SECRET}}
          node: pve3
    - PVE4:
        href: https://${PVE_1}:8006
        icon: proxmox
        description: 'Proxmox: Node 4'
        widget:
          type: proxmox
          url: https://${PVE_1}:8006
          username: {{HOMEPAGE_VAR_PVE_TOKEN_ID}}
          password: {{HOMEPAGE_VAR_PVE_1_SECRET}}
          node: pve4

- Networking:
    - Adguard:
        href: http://${ADGUARD_LXC_IP}
        icon: adguard-home
        description: Network-wide Ad-Blocker
        widget:
          type: adguard
          url: http://${ADGUARD_LXC_IP}
          username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Unifi:
        href: https://${GATEWAY_IP}
        icon: unifi
        description: Unifi Controller
        widget:
          type: unifi
          url: https://${GATEWAY_IP}
          username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
          password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

- Security:
    - Unifi Protect:
        href: https://${UNVR_IP}/protect
        icon: unifi-protect.png
        description: Home Security

- Media:
    - Agregarr:
        href: https://agregarr.local.${SECRET_DOMAIN}
        icon: sh-agregarr
        description: Plex Collection Management
        siteMonitor: http://agregarr.media.svc.cluster.local:7171
        widget:
          type: customapi
          url: http://agregarr.media.svc.cluster.local:7171/api/v1/settings/main
          refreshInterval: 60000
          headers:
            X-Api-Key: "{{HOMEPAGE_VAR_AGREGARR_TOKEN}}"
          mappings:
            - field: syncCounter
              label: Total Syncs
              format: number
            - field: lastGlobalSyncAt
              label: Last Full Sync
              format: relativeDate
            - field: lastCollectionsQuickSyncAt
              label: Last Quick Sync
              format: relativeDate
    - Autopulse:
        href: https://autopulse.local.${SECRET_DOMAIN}
        icon: https://github.com/dan-online/autopulse/raw/main/assets/logo.webp
        description: "*Arr / Plex Bridge"
        siteMonitor: http://autopulse-ui.media.svc.cluster.local:2880
        widget:
          type: customapi
          url: http://autopulse-app.media.svc.cluster.local:2875/stats
          refreshInterval: 30000
          mappings:
            - field: stats.processed
              label: Processed
              format: number
            - field: stats.pending
              label: Pending
              format: number
            - field: stats.failed
              label: Failed
              format: number
            - field: stats.retrying
              label: Retrying
              format: number
    - Maintainerr:
        href: https://maintainerr.local.${SECRET_DOMAIN}
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/maintainerr.svg
        description: Media Cleanup Tool
        siteMonitor: http://maintainerr.media.svc.cluster.local:6246
        widget:
          type: customapi
          url: http://maintainerr.media.svc.cluster.local:6246/api/collections
          refreshInterval: 60000
          mappings:
            - field: "1.mediaCount"
              label: Movies Pending
              format: number
            - field: "2.mediaCount"
              label: TV Shows Pending
              format: number
            - field: "0.mediaCount"
              label: Episodes Pending
              format: number

    - Wizarr:
        href: https://wizarr.${SECRET_DOMAIN}
        icon: wizarr.png
        description: Media Invite Management
        siteMonitor: http://wizarr.media.svc.cluster.local:5690
        widget:
          type: customapi
          url: http://wizarr.media.svc.cluster.local:5690/api/status
          refreshInterval: 60000
          headers:
            X-API-Key: "{{HOMEPAGE_VAR_WIZARR_TOKEN}}"
          mappings:
            - field: users
              label: Users
              format: number
            - field: invites
              label: Invites
              format: number
            - field: pending
              label: Pending
              format: number
            - field: expired
              label: Expired
              format: number

- Storage:
    - MinIO:
        href: http://${OMV_IP}:9001
        icon: minio
        description: Local S3 Storage
    - OpenMediaVault1:
        href: http://${OMV_IP}
        icon: openmediavault
        description: 'OpenMediaVault: Instance 1'
        widget:
          type: openmediavault
          url: http://${OMV_IP}
          username: {{HOMEPAGE_VAR_OMV1_USER}}
          password: {{HOMEPAGE_VAR_OMV1_PASS}}
          method: services.getStatus
    - OpenMediaVault2:
        href: http://${OMV2_IP}
        icon: openmediavault
        description: 'OpenMediaVault: Instance 2'
        widget:
          type: openmediavault
          url: http://${OMV2_IP}
          username: {{HOMEPAGE_VAR_OMV2_USER}}
          password: {{HOMEPAGE_VAR_OMV2_PASS}}
          method: services.getStatus