---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellarr
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: jellarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JELLARR_API_KEY: "{{ .JELLARR_API_KEY }}"
  dataFrom:
    - extract:
        key: jellyfin
