{
 "title": "Media Stack",
 "tags": [
  "media",
  "scraparr",
  "arr"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(scraparr_services_up, job)"
    }
   },
   {
    "name": "sonarr",
    "label": "Sonarr",
    "query": {
     "query": "label_values(sonarr_last_scrape{job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "radarr",
    "label": "Radarr",
    "query": {
     "query": "label_values(radarr_last_scrape{job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "prowlarr",
    "label": "Prowlarr",
    "query": {
     "query": "label_values(prowlarr_last_scrape{job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "bazarr",
    "label": "Bazarr",
    "query": {
     "query": "label_values(bazarr_last_scrape{job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "seerr",
    "label": "Seerr",
    "query": {
     "query": "label_values(seerr_last_scrape{job=~\"$job\"}, alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sonarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"sonarr\", alias=\"$sonarr\"}"
    }
   ]
  },
  {
   "title": "Radarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"radarr\", alias=\"$radarr\"}"
    }
   ]
  },
  {
   "title": "Prowlarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"prowlarr\", alias=\"$prowlarr\"}"
    }
   ]
  },
  {
   "title": "Bazarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"bazarr\", alias=\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Seerr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=~\"seerr\", alias=\"$seerr\"}"
    }
   ]
  },
  { "title": "📚 Library Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_series_total{job=~\"$job\", alias=\"$sonarr\"}"
    }
   ]
  },
  {
   "title": "Total Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episodes_total{job=~\"$job\", alias=\"$sonarr\"}"
    }
   ]
  },
  {
   "title": "Total Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"}"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_missing_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Episodes"
    },
    {
     "expr": "radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Movies"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_count{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Sonarr"
    },
    {
     "expr": "radarr_queue_count{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Radarr"
    },
    {
     "expr": "sonarr_queue_error{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Errors"
    },
    {
     "expr": "sonarr_queue_warning{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Series Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_continuing_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Continuing"
    },
    {
     "expr": "sonarr_ended_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Ended"
    },
    {
     "expr": "sonarr_upcoming_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Upcoming"
    },
    {
     "expr": "sonarr_unmonitored_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Unmonitored"
    }
   ]
  },
  {
   "title": "Movie Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_released_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Released"
    },
    {
     "expr": "radarr_in_cinemas_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "In Cinemas"
    },
    {
     "expr": "radarr_announced_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Announced"
    },
    {
     "expr": "radarr_tba_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "TBA"
    },
    {
     "expr": "radarr_unmonitored_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Unmonitored"
    }
   ]
  },
  {
   "title": "Episode Quality Profile",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_quality_episodes_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Movie Quality Profile",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_quality_movies_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  { "title": "💾 Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sonarr Used Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_disk_size_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Sonarr Free Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_free_disk_size{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Radarr Used Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_disk_size_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Radarr Free Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_free_disk_size{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "🎭 Genres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "TV Show Genres",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_genres_count_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "{{genre}}"
    }
   ]
  },
  {
   "title": "Movie Genres",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_genres_count_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "{{genre}}"
    }
   ]
  },
  { "title": "🔍 Prowlarr Indexers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_count_total{job=~\"$job\", alias=\"$prowlarr\"}"
    }
   ]
  },
  {
   "title": "Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_enabled_total{job=~\"$job\", alias=\"$prowlarr\"}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_applications_total{job=~\"$job\", alias=\"$prowlarr\"}"
    }
   ]
  },
  {
   "title": "VIP Expires",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_vip_expiration{job=~\"$job\", alias=\"$prowlarr\"} - time()"
    }
   ]
  },
  {
   "title": "Indexer Health",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "prowlarr_indexer_healthy{job=~\"$job\", alias=\"$prowlarr\"}"
    }
   ]
  },
  { "title": "💬 Bazarr Subtitles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Monitored Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_series_total{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Monitored Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_movies_total{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Wanted Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_wanted_episodes_total{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Wanted Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_wanted_movies_total{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_providers{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Provider Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "targets": [
    {
     "expr": "bazarr_provider_status{job=~\"$job\", alias=~\"$bazarr\"}"
    }
   ]
  },
  { "title": "🎬 Seerr Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_request_total{job=~\"$job\", alias=\"$seerr\"}"
    }
   ]
  },
  {
   "title": "TV Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_request_tv{job=~\"$job\", alias=\"$seerr\"}"
    }
   ]
  },
  {
   "title": "Movie Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_request_movie{job=~\"$job\", alias=\"$seerr\"}"
    }
   ]
  },
  {
   "title": "Request Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_request_tv{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "TV"
    },
    {
     "expr": "seerr_request_movie{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "Movies"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_request_status{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests per User",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(seerr_user_requests{job=~\"$job\", alias=\"$seerr\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_user_total{job=~\"$job\", alias=\"$seerr\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_issue_total{job=~\"$job\", alias=\"$seerr\"}"
    }
   ]
  },
  {
   "title": "Issue Types",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seerr_issue_type{job=~\"$job\", alias=\"${seerr}\"}\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "⚙️ Service Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Sonarr Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sonarr_start_time{job=~\"$job\", alias=\"$sonarr\"}"
    }
   ]
  },
  {
   "title": "Radarr Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - radarr_start_time{job=~\"$job\", alias=\"$radarr\"}"
    }
   ]
  },
  {
   "title": "Prowlarr Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prowlarr_start_time{job=~\"$job\", alias=\"$prowlarr\"}"
    }
   ]
  },
  {
   "title": "Bazarr Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - bazarr_start_time{job=~\"$job\", alias=\"$bazarr\"}"
    }
   ]
  },
  {
   "title": "Seerr Scrape",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (seerr_last_scrape{job=~\"$job\", alias=\"$seerr\"})"
    }
   ]
  }
 ]
}