---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  
  # Post Flux-Kustomizations
  # - ./pocket-id-operator/ks.yaml # parked until Pocket ID rollout is ready: https://github.com/vember31/home-ops/issues/4232
  - ./vaultwarden/ks.yaml
