---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
    namespace: flux-system
  interval: 1h
  values:
    controller:
      replicas: 1
    storageClass:
      create: false
