---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit-substitutions
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: bookorbit-substitutions
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BOOKORBIT_OPDS_SECRET: "{{ .BOOKORBIT_OPDS_SECRET }}"
  dataFrom:
    - extract:
        key: bookorbit
