---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-emm-user-info
  namespace: security
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: pocket-id-emm-user-info
    creationPolicy: Owner
    template:
      data:
        username: "{{ .USERNAME }}"
        firstName: "{{ .FIRST_NAME }}"
        lastName: "{{ .LAST_NAME }}"
        email: "{{ .EMAIL }}"
        displayName: "{{ .DISPLAY_NAME }}"
  dataFrom:
    - extract:
        key: pocket_id_users_emm
