---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.8.0/dist/schemas/pocketiduser_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUser
metadata:
  name: emm
  namespace: security
spec:
  userInfoSecretRef:
    name: pocket-id-emm-user-info
  admin: false
  locale: en
