---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name donetick
  namespace: home
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: donetick-secret
    creationPolicy: Owner
    template:
      data:
        DT_JWT_SECRET: "{{ .DONETICK_JWT_SECRET }}"
        DT_EMAIL_EMAIL: "{{ .DONETICK_EMAIL }}"
        DT_EMAIL_KEY: "{{ .DONETICK_EMAIL_KEY }}"

        DT_DATABASE_HOST: &dbHost postgres-18-rw.database.svc.cluster.local
        DT_DATABASE_PORT: "5432"
        DT_DATABASE_USER: &dbUser "{{ .DONETICK_POSTGRES_USER }}"
        DT_DATABASE_PASSWORD: &dbPass "{{ .DONETICK_POSTGRES_PASS }}"
        DT_DATABASE_NAME: &dbName donetick

        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: donetick
    - extract:
        key: cloudnativepg
