---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name donetick
  namespace: home

spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace

  test:
    enable: true

  rollback:
    recreate: true
    cleanupOnFail: true

  uninstall:
    keepHistory: false

  maxHistory: 1

  values:

    controllers:
      ${APP}:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: donetick-secret

        containers:
          app:
            image:
              repository: docker.io/donetick/donetick
              tag: v0.1.75@sha256:5c207a86e5425052e9ffe5286f96f71babfe57337760d303a5fb56a856790d11
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}
              DT_ENV: selfhosted
              DT_NAME: Donetick
              DT_DATABASE_TYPE: postgres
              DT_SERVER_PORT: &port 2021
              DT_SERVER_CORS_ALLOW_ORIGINS: https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}
              DT_EMAIL_HOST: smtp.gmail.com
              DT_EMAIL_PORT: "587"
              DT_EMAIL_APPHOST: https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}
              DT_OAUTH2_NAME: Pocket ID
              DT_OAUTH2_AUTH_URL: https://id.${SECRET_DOMAIN}/authorize
              DT_OAUTH2_TOKEN_URL: https://id.${SECRET_DOMAIN}/api/oidc/token
              DT_OAUTH2_USER_INFO_URL: https://id.${SECRET_DOMAIN}/api/oidc/userinfo
              DT_OAUTH2_REDIRECT_URL: https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}/auth/oauth2
              DT_IS_USER_CREATION_DISABLED: "true"
              DT_OAUTH2_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: donetick-oidc-credentials
                    key: client_id
              DT_OAUTH2_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: donetick-oidc-credentials
                    key: client_secret

            envFrom: *envFrom

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/ping
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
              startup: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *name
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-ips@kubernetescrd
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: "Task & Chore Management"
          gethomepage.dev/group: Home
          gethomepage.dev/icon: sh-donetick
          gethomepage.dev/name: Donetick

        hosts:
          - host: &host ${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

        tls:
          - secretName: ${APP}-tls-production
            hosts:
              - *host

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        globalMounts:
          - path: /donetick-data

      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
