---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage

spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 10m

  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace

  test:
    enable: true

  rollback:
    recreate: true
    force: true
    cleanupOnFail: true

  uninstall:
    keepHistory: false

  maxHistory: 1

  values:

    persistence:
      defaultClassReplicaCount: 2
      removeSnapshotsDuringFilesystemTrim: enabled

    helmPreUpgradeCheckerJob:
      enabled: true

    longhornManager:
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi

    defaultSettings:
      upgradeChecker: true
      defaultReplicaCount: "2"
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: "true"
      nodeDrainPolicy: delete-both-statefulset-and-deployment-pod
      allowCollectingLonghornUsageMetrics: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: networking-internal-with-errors@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.local.${SECRET_DOMAIN}
        hajimari.io/icon: mdi:cow
        hajimari.io/info: &description Kubernetes Storage
        hajimari.io/appName: Longhorn
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: *description
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn
        gethomepage.dev/name: Longhorn
        gethomepage.dev/href: &href https://longhorn.local.${SECRET_DOMAIN}/#/dashboard
        gethomepage.dev/app: longhorn
        gethomepage.dev/siteMonitor: *href
      host: longhorn.local.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn-tls-production

    metrics:
      serviceMonitor:
        enabled: true