---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-secret
  namespace: security
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        GMAIL_ADDRESS: "{{ .GMAIL_ADDRESS }}"
        GMAIL_APP_PASSWORD: "{{ .GMAIL_APP_PASSWORD }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: pocket_id
    - extract:
        key: maxmind
