---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.0/dist/schemas/pocketidinstance_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
  namespace: security
  labels:
    app.kubernetes.io/name: pocket-id
spec:
  deploymentType: Deployment
  appUrl: https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}
  timezone: ${TIMEZONE}
  analyticsDisabled: true
  versionCheckDisabled: true
  auditLogRetentionDays: 30
  trustedProxies:
    enabled: true
    cidrs:
      - ${POD_CIDR}
      - ${SERVICE_CIDR}
  OIDCClientRotation:
    minSpacing: 1h
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: pocket-id-secret
        key: ENCRYPTION_KEY
  geoip:
    maxmindLicenseKey:
      valueFrom:
        secretKeyRef:
          name: pocket-id-secret
          key: MAXMIND_LICENSE_KEY
  persistence:
    enabled: true
    storageClass: longhorn
    size: 1Gi
  logging:
    level: info
    json: true
  env:
    - name: SMTP_ENABLED
      value: "true"
    - name: SMTP_HOST
      value: smtp.gmail.com
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_FROM
      valueFrom:
        secretKeyRef:
          name: pocket-id-secret
          key: GMAIL_ADDRESS
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: pocket-id-secret
          key: GMAIL_ADDRESS
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pocket-id-secret
          key: GMAIL_APP_PASSWORD
    - name: SMTP_TLS
      value: starttls
  emailNotifications:
    oneTimeAccessAsAdmin: true
    verification: true
  userManagement:
    allowOwnAccountEdit: true
    allowUserSignups: disabled
  ui:
    appName: Pocket ID
    sessionDuration: 1440
    homePageUrl: /settings/account
