---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./resources/certificate.yaml
  - ./resources/ingressroute.yaml
  - ./resources/instance.yaml
