---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name shelfmark-secret

spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore  # or ClusterSecretStore

  refreshInterval: "1h"
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        HARDCOVER_API_KEY: "{{ .BOOKBOSS_METADATA_HARDCOVER_API_TOKEN }}"
        
  dataFrom:
    - extract:
        key: bookboss