---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: bookorbit-secret
    template:
      engineVersion: v2
      data:
        # bookorbit
        DATABASE_URL: "postgres://{{ .BOOKORBIT_POSTGRES_USER }}:{{ .BOOKORBIT_POSTGRES_PASS }}@postgres-18-rw.database.svc.cluster.local:5432/bookorbit?sslmode=disable"
        POSTGRES_USER: "{{ .BOOKORBIT_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .BOOKORBIT_POSTGRES_PASS }}"
        POSTGRES_DB: bookorbit
        JWT_SECRET: "{{ .BOOKORBIT_JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .BOOKORBIT_SETUP_BOOTSTRAP_TOKEN }}"

        # init-postgres
        INIT_POSTGRES_DBNAME: bookorbit
        INIT_POSTGRES_HOST: postgres-18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .BOOKORBIT_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .BOOKORBIT_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: cloudnativepg
    - extract:
        key: bookorbit
